CREATE TABLE CARGO (
  ID_CARGO NUMBER NOT NULL,
  NOME VARCHAR2(255) NOT NULL,
  PRIMARY KEY (ID_CARGO)
);

CREATE TABLE GESTOR (
  ID_GESTOR NUMBER NOT NULL,
  NOME VARCHAR2(255) NOT NULL,
  ID_CARGO NUMBER NOT NULL,
  EMAIL VARCHAR2(255) UNIQUE NOT NULL,
  SENHA VARCHAR2(255) NOT NULL,
  ATIVO CHAR(1) NOT NULL,
  PRIMARY KEY (ID_GESTOR),
	CONSTRAINT FK_GEST_CAR
    FOREIGN KEY (ID_CARGO)
      REFERENCES CARGO(ID_CARGO)
);

CREATE TABLE TRILHA (
  ID_TRILHA NUMBER NOT NULL,
  NOME VARCHAR2(255) NOT NULL,
  PRIMARY KEY (ID_TRILHA)
);



CREATE TABLE FORMULARIO (
  ID_FORMULARIO NUMBER NOT NULL,
  MATRICULA CHAR(1) NOT NULL,
  CURSO VARCHAR2(255) NOT NULL,
  INSTITUICAO VARCHAR2(255) NOT NULL,
  LGPD CHAR(1) NOT NULL,
  GITHUB VARCHAR2(255),
  LINKEDIN VARCHAR2(255),
  DESAFIOS CHAR(1) NOT NULL,
  PROBLEMAS CHAR(1) NOT NULL,
  RECONHECIMENTO CHAR(1) NOT NULL,
  ALTRUISMO CHAR(1) NOT NULL,
  RESPOSTA VARCHAR2(255),
  CURRICULO BLOB,
  TURNO VARCHAR2(255) NOT NULL,
  PROVA CHAR(1) NOT NULL,
  INGLES VARCHAR2(20) NOT NULL,
  ESPANHOL VARCHAR2(20) NOT NULL,
  NEURODIVERSIDADE VARCHAR2(255),
  CONFIG_PC VARCHAR2(255),
  EFETIVACAO CHAR(1) NOT NULL,
  DISPONIBILIDADE CHAR(1) NOT NULL,
  GENERO VARCHAR2(30) NOT NULL,
  ORIENTACAO VARCHAR2(30) NOT NULL,
  PRIMARY KEY (ID_FORMULARIO)
);

CREATE TABLE TRILHA_FORM (
  ID_TRILHA NUMBER NOT NULL,
  ID_FORMULARIO NUMBER NOT NULL,
  PRIMARY KEY (ID_TRILHA, ID_FORMULARIO),
  CONSTRAINT FK_TRILHA_FORM_ID_TRILHA
    FOREIGN KEY (ID_TRILHA)
      REFERENCES TRILHA(ID_TRILHA),
  CONSTRAINT FK_TRILHA_FORM_ID_FORMULARIO
    FOREIGN KEY (ID_FORMULARIO)
      REFERENCES FORMULARIO(ID_FORMULARIO)
);


CREATE TABLE CANDIDATO (
  ID_CANDIDATO NUMBER NOT NULL,
  ID_FORMULARIO NUMBER NOT NULL,
  NOME VARCHAR2(255) NOT NULL,
  EMAIL VARCHAR2(255) NOT NULL,
  TELEFONE VARCHAR2(30) NOT NULL,
  RG VARCHAR2(30) NOT NULL,
  CPF VARCHAR2(30) NOT NULL,
  ESTADO VARCHAR2(50) NOT NULL,
  CIDADE VARCHAR(255) NOT NULL,
  PCD CHAR(1),
  DATA_NASCIMENTO DATE NOT NULL,
  PRIMARY KEY (ID_CANDIDATO),
  	CONSTRAINT FK_FORM 
	FOREIGN KEY (ID_FORMULARIO) 
      REFERENCES FORMULARIO(ID_FORMULARIO)
);

CREATE TABLE INSCRICAO (
  ID_INSCRICAO NUMBER NOT NULL,
  ID_CANDIDATO NUMBER NOT NULL,
  DATA_INSCRICAO DATE NOT NULL,
  AVALIADO CHAR(1) NOT NULL,
  PRIMARY KEY (ID_INSCRICAO),
  	CONSTRAINT FK_CAND 
	FOREIGN KEY (ID_CANDIDATO) 
      REFERENCES CANDIDATO(ID_CANDIDATO)
);


CREATE TABLE AVALIACAO (
  ID_AVALIACAO NUMBER NOT NULL,
  ID_INSCRICAO NUMBER NOT NULL,
  ID_GESTOR NUMBER NOT NULL,
  APROVADO CHAR(1) NOT NULL,
  PRIMARY KEY (ID_AVALIACAO),
  	CONSTRAINT FK_INSC 
	FOREIGN KEY (ID_INSCRICAO) 
      REFERENCES INSCRICAO(ID_INSCRICAO),
	CONSTRAINT FK_GEST 
	FOREIGN KEY (ID_GESTOR) 
      REFERENCES GESTOR(ID_GESTOR)
);



CREATE SEQUENCE SEQ_CARGO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_GESTOR
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_AVALIACAO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_INSCRICAO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_FORMULARIO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_CANDIDATO
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

CREATE SEQUENCE SEQ_TRILHA
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

INSERT INTO CARGO (ID_CARGO, NOME)
VALUES (seq_cargo.nextval, 'ROLE_ADMINISTRADOR');

INSERT INTO CARGO (ID_CARGO, NOME)
VALUES (seq_cargo.nextval, 'ROLE_COLABORADOR');

INSERT INTO TRILHA  (ID_TRILHA, NOME)
VALUES (seq_trilha.nextval, 'FRONTEND')

INSERT INTO TRILHA (ID_TRILHA, NOME)
VALUES (seq_trilha.nextval, 'BACKEND')

INSERT INTO TRILHA (ID_TRILHA, NOME)
VALUES (seq_trilha.nextval, 'QA')

INSERT INTO GESTOR (ID_GESTOR, NOME, ID_CARGO, EMAIL, SENHA, ATIVO)
VALUES (seq_gestor.nextval, 'ADMIN', '1', 'admin@dbccompany.com.br', '123', 'T')
